from typing import TypedDict

class GameInfo(TypedDict, total=False):
    moves: int
    score: int

class FrotzEnv:
    def __init__(self, story_file: str, seed: int | None = None) -> None: ...
    def reset(self) -> tuple[str, GameInfo]: ...
    def step(self, action: str) -> tuple[str, int, bool, GameInfo]: ...
    def close(self) -> None: ...
    def get_walkthrough(self) -> list[str]: ...
