/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AblationRouteImport } from './routes/ablation'
import { Route as EvalRouteImport } from './routes/eval'
import { Route as GraveyardRouteImport } from './routes/graveyard'
import { Route as RaceRouteImport } from './routes/race'
import { Route as RulebookRouteImport } from './routes/rulebook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AblationRoute = AblationRouteImport.update({
  id: '/ablation',
  path: '/ablation',
  getParentRoute: () => rootRouteImport,
} as any)
const EvalRoute = EvalRouteImport.update({
  id: '/eval',
  path: '/eval',
  getParentRoute: () => rootRouteImport,
} as any)
const GraveyardRoute = GraveyardRouteImport.update({
  id: '/graveyard',
  path: '/graveyard',
  getParentRoute: () => rootRouteImport,
} as any)
const RaceRoute = RaceRouteImport.update({
  id: '/race',
  path: '/race',
  getParentRoute: () => rootRouteImport,
} as any)
const RulebookRoute = RulebookRouteImport.update({
  id: '/rulebook',
  path: '/rulebook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ablation': typeof AblationRoute
  '/eval': typeof EvalRoute
  '/graveyard': typeof GraveyardRoute
  '/race': typeof RaceRoute
  '/rulebook': typeof RulebookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ablation': typeof AblationRoute
  '/eval': typeof EvalRoute
  '/graveyard': typeof GraveyardRoute
  '/race': typeof RaceRoute
  '/rulebook': typeof RulebookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ablation': typeof AblationRoute
  '/eval': typeof EvalRoute
  '/graveyard': typeof GraveyardRoute
  '/race': typeof RaceRoute
  '/rulebook': typeof RulebookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ablation' | '/eval' | '/graveyard' | '/race' | '/rulebook'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ablation' | '/eval' | '/graveyard' | '/race' | '/rulebook'
  id:
    | '__root__'
    | '/'
    | '/ablation'
    | '/eval'
    | '/graveyard'
    | '/race'
    | '/rulebook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AblationRoute: typeof AblationRoute
  EvalRoute: typeof EvalRoute
  GraveyardRoute: typeof GraveyardRoute
  RaceRoute: typeof RaceRoute
  RulebookRoute: typeof RulebookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ablation': {
      id: '/ablation'
      path: '/ablation'
      fullPath: '/ablation'
      preLoaderRoute: typeof AblationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eval': {
      id: '/eval'
      path: '/eval'
      fullPath: '/eval'
      preLoaderRoute: typeof EvalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graveyard': {
      id: '/graveyard'
      path: '/graveyard'
      fullPath: '/graveyard'
      preLoaderRoute: typeof GraveyardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/race': {
      id: '/race'
      path: '/race'
      fullPath: '/race'
      preLoaderRoute: typeof RaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rulebook': {
      id: '/rulebook'
      path: '/rulebook'
      fullPath: '/rulebook'
      preLoaderRoute: typeof RulebookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AblationRoute: AblationRoute,
  EvalRoute: EvalRoute,
  GraveyardRoute: GraveyardRoute,
  RaceRoute: RaceRoute,
  RulebookRoute: RulebookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
